### ISSUE TITLE
AttributeError: 'Bot' object has no attribute 'notifyOnMessage'

### ISSUE THREAD

**Issue by evanalexaaaa** [EhsanFox/MusicBot#1]
Traceback (most recent call last):
  File "D:/work_dir/Android_Test/test_project/music.py", line 110, in <module>
    bot.notifyOnMessage(handleBotMessage)
AttributeError: 'Bot' object has no attribute 'notifyOnMessage'

**Comment by evanalexaaaa** [comment]
Traceback (most recent call last):
  File "D:/work_dir/Android_Test/test_project/music.py", line 110, in <module>
    bot.notifyOnMessage(handleBotMessage)
AttributeError: 'Bot' object has no attribute 'notifyOnMessage'
